services:
#  frontend-dev:
#    build: ./frontend-dev/
#    volumes:
#      - ./frontend-dev:/app/
#    profiles: ["dev"]
#    ports:
#      - "3000:3000"
#    # run interactive
#    stdin_open: true  # docker run -i
#    tty: true         # docker run -t
#
#  frontend-prod:
#    build: ./frontend-prod/
#    profiles: ["prod"]
#    ports:
#      - "80:80"
#
#  backend-dev:
#    build: ./backend-dev/
#    volumes:
#      - ./backend-dev:/app/
#    profiles: ["dev"]
#    ports:
#      - "5000:5000"
#    environment:
#      NODE_ENV: "development"
#      PORT: "5000"
#      MONGO_HOST: "localhost"
#      MONGO_PORT: "27017"
#      MONGO_DB_NAME: "stretchSmart"
#    secrets:
#      - mongo_root_username
#      - mongo_root_password
#    # run interactive
#    stdin_open: true  # docker run -i
#    tty: true         # docker run -t
#
#  backend-prod:
#    build: ./backend-prod/
#    profiles: ["prod"]
#    ports:
#      - "5000:5000"

  database:
    build: ./database
    # Ports only need to be exposed for development ease,
    # all services in the same network can communicate.
    # In production, the database should not be exposed.
    volumes:
      - ./database/data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
    secrets:
      - mongo_root_username
      - mongo_root_password
    restart: always

secrets:
  mongo_root_username:
    file: ./secrets/mongo_root_username
  mongo_root_password:
    file: ./secrets/mongo_root_password

